#!/bin/bash

# important: set pipefail bash option, see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eo pipefail

# import global utils
source utils.sh

# initialize global utils
init_log
mkdir -p "${TEMP_DIR}"
#mktemp -d "${TEMP_DIR}"
trap end_sigint SIGINT

log_info "= Make sure programs I always need are installed"
log_info "== (Unattended) Refresh APT-Sources"
apt_get_without_interaction "update" | log_debug_output

log_info "== (Unattended) Install Tools available in the default debian-buster repository"
apt_get_without_interaction "install" "sudo \
    man \
    dos2unix \
    git \
    nano \
    neofetch \
    screenfetch \
    htop \
    dialog \
    ffmpeg \
    ranger \
    exa \
    tree \
    lolcat" | log_debug_output

log_info "== (Unattended) Install of 'gimmick' Tools available in the default debian-buster repository..."
apt_get_without_interaction "install" "cmatrix" | log_debug_output

log_info "== Checking if sdkman is installed for user ${USER}..."
if hash sdk 2>/dev/null; then
  log_debug "== SDKMan! already installed:"
  sdk version | log_info
else
  # https://sdkman.io/install
  log_info "== (Unattended) Install of sdkman..."
  curl -s "https://get.sdkman.io?rcupdate=false" | bash | log_debug_output
  source "${HOME}/.sdkman/bin/sdkman-init.sh" | log_debug_output
  sdk version | log_info
fi

log_info "== Creating aliases..."
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'

log_info "= Starting mainmenu-loop"
while :
do
  log_info "= Starting mainmenu"
  . mainmenu.sh
done




#
end_gracefully