#!/bin/bash

# important: set pipefail bash option, see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eo pipefail

# import global utils
source utils.sh

# initialize global utils
init_log
mkdir -p "${TEMP_DIR}"
#mktemp -d "${TEMP_DIR}"
trap end_sigint SIGINT

# TODO check if this also accepts if the script gets run from another user using sudo
# Check if running as root
if [[ "$EUID" -ne 0 ]]; then
  log_error "Please run the script as root."
  backup_log
  exit 1
fi

log_info "= Make sure programs I always need are installed"
log_info "== (Unattended) Refresh APT-Sources"
apt_get_without_interaction "update" | log_debug_output

log_info "== (Unattended) Install Tools available in the default debian-buster repository"
apt_get_without_interaction "install" "sudo \
    man \
    dos2unix \
    git \
    nano \
    neofetch \
    screenfetch \
    htop \
    dialog \
    ffmpeg \
    ranger \
    exa \
    lolcat" | log_debug_output

log_info "== (Unattended) Install of 'gimmick' Tools available in the default debian-buster repository..."
apt_get_without_interaction "install" "cmatrix" | log_debug_output




log_info "= Starting mainmenu-loop"
while :
do
  log_info "= Starting mainmenu"
  . mainmenu.sh
done




#
end_gracefully